word = input("Enter the text here\n")
clean_text = word.strip()
remove_space = clean_text.replace(" ","")
caseInsensitive = remove_space.lower()
print("Total number of unique char is ",len(set(caseInsensitive)))
